### ISSUE TITLE
UI Improvements Contributor Profiles and Listing

### ISSUE THREAD

**Issue by tillprochaska** [tactilenews/100eyes#1004]
This is a collection of multiple minor UI issues.

The contributor profiles UI has evolved in a somewhat unstructured way. The currently UI has some problems and potential for improvements:

- [x] **1) Master data vs. communication channel preferences**
   It’s unclear which fields are merely a way to store additional information about a contributor vs. which fields are used to send messages to contributors. For example, an editor reported they wanted to simply store an email address in a contributor’s profile as additional information. They did not expect that this would cause the contributor to receive all messages via email.
   
   We should probably separate the fields that store communication channel information and those that store master data that isn’t used for anything else. We should also add help texts where appropriate to set clear expectations.

||||
|-|-|-|
|![profil_email](https://user-images.githubusercontent.com/1512805/133920295-d75101b9-e543-4107-abab-1191957ac80d.png)|![profil_inaktiv](https://user-images.githubusercontent.com/1512805/133920298-3ddadce2-baa0-4724-9dda-310d848b4cea.png)|![profil_onboarding](https://user-images.githubusercontent.com/1512805/133920303-06034fc4-046d-4390-bd5c-bbd37135b07b.png)|

- [x] **2) Display note/warning if contributor hasn’t completed onboarding**
   Telegram and Signal have a two-step onboarding process where contributors need to send us an initial message. We should display a warning if a contributor hasn’t completed the last step, with instructions for editors how they can support contributors in completing the process. For example, if a contributor hasn’t completed Telegram onboarding, we’d display something like this:

   > "Dieses Mitglied hat sich per Telegram angemeldet, das Onboarding aber noch nicht abgeschlossen. Unter [diesem Link](#) findet das Mitglied eine Anleitung, um das Onboarding abzuschließen."

- [x] **3) Filter contributor listing by active/inactive contributors**
   Currently, the listings page for contributors lists all contributors, wether they are active or inactive. This is confusing, as the listings don’t indicate which contributors are active/inactive (i.e. you have to visit the contributor profile to see the status). Also, the total number of contributors includes inactive contributors, which might give you a false impression of the community size.

   ![](https://user-images.githubusercontent.com/1512805/97787897-2cd32e00-1bb5-11eb-8e2d-4753091e2080.png)
https://github.com/tactilenews/100eyes/pull/464#issuecomment-719975476

- [x] **4) Use more subtle styles for tag pills**
   Tag pills currently have solid, very colorful backgrounds. This can make the contributor listings a little overwhelming/hard to scan. Also, foreground/background contrasts are bad for some colors. We could style tags a little less prominent, while keeping colored tags, something in this direction:

   <img width="446" alt="Screen Shot 2021-08-13 at 12 53 18" src="https://user-images.githubusercontent.com/1512805/129346726-be56ea82-3e93-42e1-a246-844d37fd248a.png">

**Comment by drjakob** [comment]
1) Please just show the active communication-channel field (only "Threema" or "Telegram")!
2) good solution ( Probably we can show a "User remaining on your plan) )
3) Tag color should be consistent, so "Entwickler" is always green.
