### ISSUE TITLE
Display "via Telegram" for contributors that have started, but not completed Telegram onboarding

### ISSUE THREAD

**Issue by tillprochaska** [tactilenews/100eyes#1039]

**Comment by phoeinx** [comment]
I think we at some point discussed having some sort of marker for contributor profiles that have started but not completed Telegram onboarding. I couldn't find an issue right away for that, but maybe it would make sense to display something specific for not completed onboarding here? Like `via Telegram (Onboarding incomplete)` or so?

**Comment by tillprochaska** [comment]
@phoeinx Yes, I agree, but I’d like to do this in a way that has a good UX (i.e. has instructions for editors how they can support contributors) and works for all channels. In the meantime, I think we could still display `via Telegram` as what we have right now is clearly a little buggy.

A possible downside of fixing this while not adding a hint for incomplete onboarding is that there wouldn’t be a way for contributors to find users with incomplete onboarding anymore in the meantime? (But not sure if they’ve been aware of this at all…)

**Comment by phoeinx** [comment]
@tillprochaska, I see your point there. A better UX is definitely needed, but if we don't have the time to implement this soon-ish, I think something like this might be an interim fix.  For me, this depends on how soon we'll be able to implement a real fix. Or do you think that a quick fix like this would not add value, but rather confusion?

I think that Users will actually be able to still detect incomplete Telegram onboardings - if you have sign-up `via Telegram` but not Telegram username is displayed, that should be a not completed Telegram Sign-Up. (This, of course, would require going through all Telegram contributors.)

A more general question:
Can we have incomplete onboardings for the other channels? For Signal, yes, but we cannot detect this currently and would need to add logic to see whether, we've already received a message. 
But are incomplete Email and/or Threema onboardings possible?

**Comment by tillprochaska** [comment]
> I think that Users will actually be able to still detect incomplete Telegram onboardings - if you have sign-up via Telegram but not Telegram username is displayed, that should be a not completed Telegram Sign-Up. (This, of course, would require going through all Telegram contributors.)

That doesn’t work reliably, because you can use Telegram without a username.

> For me, this depends on how soon we'll be able to implement a real fix. 

I was planning to look into this rather soon, at least as long as there's nothing urgent popping up.

> A more general question:
Can we have incomplete onboardings for the other channels? For Signal, yes, but we cannot detect this currently and would need to add logic to see whether, we've already received a message.
But are incomplete Email and/or Threema onboardings possible?

No, incomplete onboarding for email and Threema are not possible. Regarding Signal, I guess we’d have to add that extra logic anyways in the near future so we can give contributors proper feedback once we’ve received the initial message.
