### ISSUE TITLE
Show number of recipients after pressing "send request" button

### ISSUE THREAD

**Issue by FrauCsu** [tactilenews/100eyes#106]
As editor I want to be sure, how many users received my message. So I need the confirmation "Your message was sucessfully sent to ((Number)) users."
"All" does not tell me, how many.

**Comment by FrauCsu** [comment]
Merge issue with issue #111 
it is basically the same - showing number of recipients and number of answers like

(0/50)
(18/43)
... @tillprochaska @drjakob

**Comment by tillprochaska** [comment]
Technically, this is actually quite different and also a different UI element, so let’s keep this open.

**Comment by drjakob** [comment]
Yes, its a different feature. This is just a confirmation.

**Comment by tillprochaska** [comment]
We might also reconsider the wording. At the time the message is shown, messages haven’t actually been sent yet. Something along the lines of "Wir senden deine Frage jetzt an xy Community-Mitglieder" would be more precise.

**Comment by FrauCsu** [comment]
Yes.

Till Prochaska <notifications@github.com> schrieb am Mo., 29. Juni 2020,
17:16:

**Comment by roschaefer** [comment]
closed in #400
