### ISSUE TITLE
Update footer

### ISSUE THREAD

**Issue by tillprochaska** [tactilenews/100eyes#1063]
1. Change "Ein Projekt von" to "Ein Service von"
2. Remove third column (license)

**Comment by tillprochaska** [comment]
@FrauCsu Soll da dann auch gleich schon GmbH anstellen von OHG stehen?

**Comment by FrauCsu** [comment]
tactile.news GmbH

**Comment by drjakob** [comment]
Ja

-- 
Dr. Jakob J. E. Vicari
Freelance Creative Technologist
***@***.***
+49 (0)4131 799 85 61

Reporterpreis 2019, Kategorie Multimedia
Ernst-Schneider-Preis 2018, Innovation

*** NEU: Das Buch ***
Journalismus der Dinge. Strategien für den Journalismus 4.0
Herbert von Halem Verlag. Jetzt bestellen: www.halem-verlag.de/journalismus-der-dinge
