### ISSUE TITLE
Write default text modules to add to requests via checkboxes

### ISSUE THREAD

**Issue by FrauCsu** [tactilenews/100eyes#112]
As editor I need default text modules
I can add to my new request 
by clicking check-boxes
(Textbaustein Fotos, Textbaustein medizinische Informationen,...)

**Comment by FrauCsu** [comment]
Find our text modules in Slack

**Comment by FrauCsu** [comment]
Textbausteine für 100eyes Vorlagen


Foto
Schicken Sie uns doch auch ein Foto (oder mehrere). 
Bitte schicken Sie nur Fotos, die Sie selber gemacht haben, am besten im jpeg-Format. Beschriften Sie die Foto-Dateien mit Ihrem Namen. Mit der Zusendung von Fotos geben Sie gleichzeitig Ihr Einverständnis für eine mögliche Veröffentlichung. Bei Veröffentlichung nennen wir Sie als Urheber (Foto: Max Mustermann/100eyes). 

Adresse
Schicken Sie uns doch eine Adresse oder genaue Koordinaten. 
Wir nutzen die Geodaten für unsere Recherchen und werden sie eventuell in einem Text verarbeiten oder als Datenpunkt auf einer Karte verwenden. 

Kontaktdaten
Schicken Sie uns gerne Kontaktdaten. 
Wir nutzen die Kontaktdaten für unsere Recherchen und werden die Person eventuell kontaktieren, aber keine Kontaktdaten veröffentlichen.

Medizinische Informationen
Sie stellen uns hier möglicherweise sensible medizinische Informationen bereit. 
Wir sind uns dessen bewusst und behandeln Ihre Daten mit aller gebotenen Vorsicht. Wenn Sie uns Daten schicken, helfen uns diese Informationen für unsere weiteren Recherchen. Ihre Daten werden wir nur intern auswerten, aber  nicht veröffentlichen. Es sei denn, Sie geben Ihr ausdrückliches Einverständnis, nachdem wir Sie separat darum gebeten haben.

Vertrauliche Informationen
Sie stellen uns hier möglicherweise vertrauliche Informationen bereit. 
Wir sind uns dessen bewusst und behandeln diese Informationen mit aller gebotenen Vorsicht. Wir werden Ihre Informationen nur intern auswerten, aber nicht ungefragt veröffentlichen.

**Comment by tillprochaska** [comment]
> Bitte schicken Sie nur Fotos, die Sie selber gemacht haben, am besten im jpeg-Format.

Ist das relevant? Ich bezweifle, dass überhaupt alle Nutzer wissen, was JPEG ist bzw. wie sie auf ihrem Handy das richtige Format bekommen. Ist es so wichtig, welches Format die Bilder haben? Falls es wichtig ist, sollte sich 100eyes nicht darum kümmern, sie im Zweifel zu konvertieren?

> Beschriften Sie die Foto-Dateien mit Ihrem Namen.

Ähnliche Frage, wie soll das funktionieren? Falls es darum geht, dass heruntergeladene Fotos den Namen der Lokalexpert*innen im Dateinamen tragen, so könnten wir das vermutlich besser automatisch lösen.

**Comment by FrauCsu** [comment]
Stimmt. Also: Die Parts löschen.
Aber: Dann das Beschriften der Bilddateien mit den 100eyes-Namen automatisch lösen.

**Comment by tillprochaska** [comment]
Ich habe das mal als separates Issue in #127 aufgenommen. Schau doch noch mal drüber, ob das so passt.

**Comment by FrauCsu** [comment]
Ja, das finde ich sehr gut so.
