### ISSUE TITLE
Check linkedIn

### ISSUE THREAD

**Issue by drjakob** [tactilenews/100eyes#1245]
As an editor, I also want to write direct messages to my communities on LinkedIn to enable business communication.
Please check how much effort this is and what constrains are there.

**Comment by tillprochaska** [comment]
LinkedIn has a [Messaging API](https://docs.microsoft.com/en-us/linkedin/shared/integrations/communications/messages?context=linkedin%2Fcompliance%2Fcontext). It is "restricted to approved partners, subject to limitations via API agreement.". As the API is part of their compliance solutions, I’d assume that using it for our use case would be out of scope.
