### ISSUE TITLE
Improve replies/request activity in user profile

### ISSUE THREAD

**Issue by tillprochaska** [tactilenews/100eyes#125]
Currently, the listing of requests a user has replied to is confusing – it mixes the title of the request with the replies of the user.

<img width="920" alt="Screenshot 2020-05-22 11 37 29" src="https://user-images.githubusercontent.com/1512805/82654228-afc48580-9c20-11ea-9e86-0f13f8c06aa5.png">

As there already is a possibility to show all replies of a user for a specific, we don’t necessarily need to show all of the replies in the user profile. Instead we could just show their activity, i.e. the time a user has replied to a certain request. Clicking on this activity item would then show the complete conversation.

![IMG_4366](https://user-images.githubusercontent.com/1512805/82654145-915e8a00-9c20-11ea-934b-d00433f95c80.jpg)

**Comment by FrauCsu** [comment]
AGREED.

**Comment by tillprochaska** [comment]
Feedback appreciated. I think the second variant works better than the first one – I guess the most important information is the request a user replied to, so that should come first.

**Variant 1**
<img width="933" alt="Screenshot 2020-05-22 15 40 06" src="https://user-images.githubusercontent.com/1512805/82674005-f75c0900-9c42-11ea-80a0-fe1ef4e2c5b1.png">

**Variant 2**
<img width="956" alt="Screenshot 2020-05-22 15 41 10" src="https://user-images.githubusercontent.com/1512805/82673998-f3c88200-9c42-11ea-8ea2-1df3a1351efa.png">

**Comment by FrauCsu** [comment]
Journalism is news and often time-sensitive. If we take quick news gathering into account, the time stamp is important. So I'd go for variant 1

**Comment by tillprochaska** [comment]
Gilt das immer noch, wenn du den Use Case für die Profilseite betrachtest? Du dient doch eher dazu, mehr über Lokalexpert*innen herauszufinden, um die Person besser einschätzen zu können, oder? Für aktuelle/zeitkritische Infos ist doch eher die entsprechende Fragen-Übersicht die Anlaufstelle, oder?

**Comment by FrauCsu** [comment]
Da hast du Recht. Bin vom Gegenteil überzeugt. Variante 2.
