### ISSUE TITLE
Email adapter: Sender name isn’t set correctly when updated via the UI

### ISSUE THREAD

**Issue by tillprochaska** [tactilenews/100eyes#1276]
**To reproduce:**

1. Open the 100eyes web UI.
2. Visit `/settings`.
3. Change the project name to something new.
4. Trigger any action that sends an email, e.g. send a new question.
5. The email uses the old project name as the sender.

However, this might as well affect other use cases where tasks are executed in background jobs.

**Why this happens:**

* Emails are sent in a background job, i.e. in a worker process that is different from the web server process.
* Settings aren’t cached once they’ve been fetched from the database for the first time.
* Caching using the default in-memory store is obviously not safe to use across multiple processes.

**Potential solutions:**

1. We could ensure that background jobs never never retrieve settings from the cache.
2. We could use a centralized cache store (Redis, …).

I think I’d prefer solution 1 here, although it’s a somewhat hacky solution. However, there should be only a handful of cases at max where this is relevant and the additional overhead of an  additional database request is negligible. This might be as easy as adding [a callback](https://api.rubyonrails.org/v7.0.2.3/classes/ActiveJob/Callbacks/ClassMethods.html#method-i-before_perform) to our `ApplicationJob` that always [resets the settings cache](https://github.com/huacnlee/rails-settings-cached/blob/main/lib/rails-settings/base.rb#L35) before any job is performed.

**Comment by roschaefer** [comment]
Yes, I also prefer solution 1 in order not to pull in more dependencies. The suggested idea with the callback is exactly what I would do in JavaScript land. Don't know what's the idiomatic solution for this in ruby but I guess we could apply it there, too.

**Comment by tillprochaska** [comment]
In order to reproduce this in your development environment, make sure to enabled caching using the following command. Then restart your Rails server!

```
bin/rails dev:cache
```
