### ISSUE TITLE
Follow-up for additional consent check boxes

### ISSUE THREAD

**Issue by phoeinx** [tactilenews/100eyes#1283]
As a follow up to #1274 the following refactorings/features should or could still be implemented:

#### Refactoring & Fixes
- [x] Create a consent checkbox component to reduce code duplication / general amount of code in onboarding forms.
- [x] Fix that with a very short heading and text the checkbox is right-aligned.  

#### Features
- [x] Implement CSV export of user data. See #190.
- [ ] Optionally add a section to the contributor profile that shows the given additional consent status of the contributor.
- [ ] The additional consent text can so far not support pretty links etc. It might be worthwhile to implement it with a markdown field if users would like to link to an external document. See the screenshot where the `Datenschutzerklärung` is linked to an external document, which is currently not possible for the additional consent field (which currently also doesn't display clickable links).
<img width="300" alt="image" src="https://user-images.githubusercontent.com/34538290/160384934-68e3867e-230f-4c3c-9297-dbd59bd76f9e.png">

**Comment by phoeinx** [comment]
@FrauCsu @drjakob Which of the possible follow-ups would you prioritize at the moment?

**Comment by FrauCsu** [comment]
@phoeinx I would reduce amount of work and choose quick fix with short header and text alignment and add the csv feature so newsrooms can work with the additional consent. 
I would also add another fix: The additional consent box should not be accessable in the settings for all users but only for admins in their dashboard. Should we write a new issue for that @drjakob ?

**Comment by tillprochaska** [comment]
@phoeinx I can’t see the need for for links/markup in consent labels so far, so I wouldn’t implement that until we have a use case for that. Extracting consent checkboxes into a separate component shouldn’t take too long and is definitely sensible, as the amount of code duplication will only grow once we add new communication channels.

**Comment by tillprochaska** [comment]
I think this can be closed now that we have the CSV export!
