### ISSUE TITLE
Validating Threema IDs against Threema Gateway during Onboarding

### ISSUE THREAD

**Issue by drjakob** [tactilenews/100eyes#1351]
Additionally, we might consider validating Threema IDs against Threema Gateway API during onboarding

**Comment by mattwr18** [comment]
Isn't this a duplicate of https://github.com/tactilenews/100eyes/issues/723 @drjakob ? Can we close this in favor of that issue since it was created first and has additional info?

**Comment by mattwr18** [comment]
Closing this as it has been 3 months since the :point_up: was asked and it seems to be a duplicate.
