### ISSUE TITLE
Messages are not received in any channel while running the background jobs in dockerized env

### ISSUE THREAD

**Issue by mattwr18** [tactilenews/100eyes#1381]
We recommend using docker for development in our README, yet receiving requests does not work in any channel while doing so.
After debugging, the issue is with the jobs worker. Running services locally, devs are able to send and receive messages as expected.

### Steps to reproduce:
1. git checkout master
2. git pull origin master
3. docker compose build
4. docker compose up
5. Sign up with any channel(haven't tested signal)
6. Send request
7. Oh no, nothing is received.

### Expectation: 
That we either not recommend using docker for local development as it seems none of our devs actually use it, or that we keep it maintained.

#### Steps to receive messages
1. Run rails server locally. 
```bash
$ bundle exec rails server
```

2. Run local postgres, or start service
```bash
$ docker-compose up db
```

3. To receive email, start mailserver service.
```bash
$ docker-compose up mailserver
```

4. To receive Telegram messages.
    - Setup webhooks with:
	  ```bash
	      $ bin/rails telegram:bot:set_webhook
	  ```
	  Note: at the time of writing this issue, this results in an:
	  
	  > ArgumentError: Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true.
	  
	  See https://github.com/telegram-bot-rb/telegram-bot/issues/13
    - Onboard as a Telegram contributor.
 
5. To receive Threema messages.
   - Onboard as a Threema contributor.

6. To receive Signal messages.
    - ???

**Comment by tillprochaska** [comment]
Hey, you’re right, you would need to have a worker running for any tasks that are run asynchronously in background jobs to be executed. This is the case for all actions that send out messages, and it is also the case for receiving messages, depending on the channel. (Signal messages are polled in a background job, whereas emails, Threema, and Telegram messages are received via a webhook request.)

Running `docker compose up` will also start the `jobs-worker` service, so you should be all set if you use that. If you start only the `app` service using `docker compose app`, then you’d have to manually start the `jobs-worker` service using `docker compose up jobs-worker`.

**Comment by tillprochaska** [comment]
> To receive email, start mailserver service.

I think this might be a misunderstanding. The `mailserver` service is an SMTP server (i.e. it can only be used to send messages). It’s only purpose is to "fake" a real SMTP server, allowing you to inspect emails that are sent during development.

**Comment by mattwr18** [comment]
> Running docker compose up will also start the jobs-worker service, so you should be all set if you use that. 
Should, but it doesn't work. which is why I created this issue. I can see that the `jobs-worker` server is started, but it doesn't handle the jobs.

**Comment by tillprochaska** [comment]
Could you provide some log output from the `jobs-worker` service? I can’t reproduce this.

**Comment by mattwr18** [comment]
> Could you provide some log output from the jobs-worker service? I can’t reproduce this.

The thing is that I don't see any log output at all when running `docker compose up` locally. On any services.

**Comment by tillprochaska** [comment]
You can run `docker compose logs {{SERVICE_NAME}}` to print the log output. You can also include the `--follow/-f` flag to keep the process running to see new log items as they are created.

https://docs.docker.com/engine/reference/commandline/compose_logs/

**Comment by mattwr18** [comment]
> You can run `docker compose logs {{SERVICE_NAME}}` to output logs for a particular service. You can also include the `--follow/-f` flag to keep the process running to see new log items as they are created.
> 
> [docs.docker.com/engine/reference/commandline/compose_logs](https://docs.docker.com/engine/reference/commandline/compose_logs/)

Oh nice, thanks for the tip. I'll get back to you.

**Comment by tillprochaska** [comment]
Sorry, that was indeed a misunderstanding, but on my end. I thought you were talking about receiving emails *from* contributors, i.e. inbound email.

**Comment by mattwr18** [comment]
Closing this issue as I can receive messages from all channels now, I guess.
