### ISSUE TITLE
Handle `Postmark::InactiveRecipientError` exceptions in mail delivery jobs

### ISSUE THREAD

**Issue by tillprochaska** [tactilenews/100eyes#1382]
Currently, these exceptions aren’t handled explicitly. The exceptions get reported to Sentry (which is a good thing), but they end up in our main monitoring channel.

Instead, we should handle this exception and report it to Sentry with an additional tag (e.g. support). We can then configure Sentry to send notifications about issues tagged with "support" into a separate channel without involvement from developers.

**Comment by tillprochaska** [comment]
This is related to #725. However, the goal of #725 is to have a consistent solution across channels. This ticket would be a short-term solution to make it easier to handle monitoring notifications.

**Comment by mattwr18** [comment]
I think it makes sense to also add the Threema errors [100EYES-3K](https://sentry.io/organizations/tactilenews/issues/3349022907/?project=5686596&query=is%3Aunresolved) to this issue as well since they are essentially the same.

**Comment by mattwr18** [comment]
> I think it makes sense to also add the Threema errors [100EYES-3K](https://sentry.io/organizations/tactilenews/issues/3349022907/?project=5686596&query=is%3Aunresolved) to this issue as well since they are essentially the same.

Working on the `Postmark::InactiveRecipientError` issue, I decided that it would be best to keep the Threema issue separate to keep the PR smaller. See https://github.com/tactilenews/100eyes/issues/1448
