### ISSUE TITLE
Button inserting {first_name}

### ISSUE THREAD

**Issue by drjakob** [tactilenews/100eyes#1407]

**Comment by drjakob** [comment]
fixing cursor displaying bug in test system

**Comment by mattwr18** [comment]
> fixing cursor displaying bug in test system

As [reported in Slack](https://tactilenews.slack.com/archives/C010QDQLCKW/p1661419892971119), the client has been unable to reproduce the issue and so have we.

**Comment by FrauCsu** [comment]
Can this issue be closed?
