### ISSUE TITLE
Update Alpine version

### ISSUE THREAD

**Issue by tillprochaska** [tactilenews/100eyes#1411]
We’re using an outdated version of Alpine.

For context, see #1410 and #1409.

**Comment by roschaefer** [comment]
We cannot update Linux Alpine unless we're also updating `postgresql-client` as well. Alpine Linux does not come with it anymore, see here: 
https://pkgs.alpinelinux.org/packages?name=postgresql-client&branch=v3.12&repo=&arch=&maintainer=
https://pkgs.alpinelinux.org/packages?name=postgresql-client&branch=v3.13&repo=&arch=&maintainer=
