### ISSUE TITLE
[Signal] Handle uuid sender identification

### ISSUE THREAD

**Issue by phoeinx** [tactilenews/100eyes#1427]
Signal / Signal-cli now allows identifying senders only by UUIDs, which makes us unable to identify contributors' first messages. (100EYES-3M)
As Till found out this can be resolved by creating contacts for each Signal contributor during onboarding, from which signal-cli can infer the UUIDs.

**Comment by mattwr18** [comment]
This was closed by [#1428](https://github.com/tactilenews/100eyes/pull/1428), right?
