### ISSUE TITLE
Answers of some contributors are counted double in dashboard

### ISSUE THREAD

**Issue by phoeinx** [tactilenews/100eyes#1499]
Even though I just sent one request and got exactly one message in reply:
![image](https://user-images.githubusercontent.com/34538290/194587033-c7c0568d-e53d-42e9-9856-be1637183703.png)

The dashboard tells me that the contributor who sent the one message actually sent a message twice? Either way it wouldn't make sense to name the contributor twice here right?
![image](https://user-images.githubusercontent.com/34538290/194587212-363c570a-75bd-4039-be55-4a721b2d0679.png)

This then also affects the data in the time dashboard:
![image](https://user-images.githubusercontent.com/34538290/194587266-82a4409d-2f38-40d8-b83d-8db4221b3e87.png)

**Comment by mattwr18** [comment]
That is super weird @phoeinx and I'm not sure how to replicate it. We do have automated tests that check this and run every time a PR is put in and a commit is pushed to it. I have also personally never seen this.

I wonder if you are able to reproduce this and if you have some steps to reproduce it.

**Comment by phoeinx** [comment]
Hi, sadly there were some changes in my local db (I had to recreate a user) and I also could not reproduce this anymore.
Let's maybe put this on hold until we see it again?

**Comment by mattwr18** [comment]
> Hi, sadly there were some changes in my local db (I had to recreate a user) and I also could not reproduce this anymore.
Let's maybe put this on hold until we see it again?

Hey, sorry that it's taken so long to respond. I saw this message, but forgot to respond. Yeah, I will close this and let's see if we can reproduce it first.
