### ISSUE TITLE
Add Sender info to the `ChatMessages`

### ISSUE THREAD

**Issue by mattwr18** [tactilenews/100eyes#1506]
```
As an editor
I would like to see which of my colleagues has sent out a ChatMessage directly from the Request show page/contributor_request_path
So that it's clear who sent the message
```

**Comment by drjakob** [comment]
Yes, please share a mockup!

**Comment by FrauCsu** [comment]
Can be on paper, too :-)

**Comment by mattwr18** [comment]
I guess it would look something like this:

![Screenshot from 2022-10-18 08-41-41](https://user-images.githubusercontent.com/26943915/196354734-4f319caf-d279-42f6-b5da-b976d2de8aea.png)

At the moment, I am not sure what else information would be helpful other than the editor's name. I included the avatar, as I did in the activity feed because it looks strange UI wise to have some rows with the avatar and others without, but as we don't give the ability for Users  to upload images, it would always be their initials. Maybe instead of the tags list we display for the contributors, we could displays some metrics, like how many requests, how many personal messages they sent, etc..
