### ISSUE TITLE
BUG image counter broken

### ISSUE THREAD

**Issue by drjakob** [tactilenews/100eyes#1532]
The Image counter seems broken as there are not all pictures, that have been sent in from contributors, being counted as pictures. Affecting not only Threema but also Signal and E-Mail.

**Comment by FrauCsu** [comment]
Please put in a fix. Possible before deploying on sunday @mattwr18 ?

**Comment by mattwr18** [comment]
This is a duplicate issue. I can link to it later, but I think we should close this in favor of the older issue.

**Comment by mattwr18** [comment]
Here is the original issue https://github.com/tactilenews/100eyes/issues/813. The fix is related to another issue https://github.com/tactilenews/100eyes/issues/1387 and is not something that can be quickly done.

**Comment by FrauCsu** [comment]
related to #996 996 und #813 @mattwr18

**Comment by mattwr18** [comment]
Closed via https://github.com/tactilenews/100eyes/pull/1538
