### ISSUE TITLE
UX-Request Changing the image – changing the button

### ISSUE THREAD

**Issue by drjakob** [tactilenews/100eyes#1533]
When I selected an image and uploaded it, the button text should change. "Bild wechseln" (change image) instead of  "Bild anhängen" ("Attach image".)

**Comment by drjakob** [comment]
<img width="904" alt="Bildschirm­foto 2022-11-18 um 09 54 27" src="https://user-images.githubusercontent.com/11591426/202662151-a7dde39e-a5c1-4212-9097-68ca80cf7e58.png">

**Comment by FrauCsu** [comment]
Don't code, discuss first. @mattwr18 @drjakob

**Comment by mattwr18** [comment]
Closing this as we discussed this and don't feel like it's necessary after adding the filenames. Also, we would like to get client feedback before doing something like this.
