### ISSUE TITLE
Unsubscribe Feature for Community-Members in all messengers channels

### ISSUE THREAD

**Issue by drjakob** [tactilenews/100eyes#1637]
We have a unsubscribe-feature for Whatsapp. We need one for Signal, Telegram and Threema. (Open question: How would they know?)

**Comment by mattwr18** [comment]
Also discussed in the standup, we can add this information to the onboarding success message. It's not a perfect solution since existing contributors will not receive this message, but we could maybe combine some approaches :shrug:
