### ISSUE TITLE
Revise function "Hinweise anhängen"

### ISSUE THREAD

**Issue by drjakob** [tactilenews/100eyes#166]
As an editor, the "attach notes"("Hinweise anhängen") function bothers me because it is very prominent, I don't understand it and it keeps me from asking a question.

**Comment by FrauCsu** [comment]
Delete "Hinweise anhängen". It needs to be done during the onboarding process @tillprochaska @drjakob

**Comment by tillprochaska** [comment]
Are you sure you want to remove that feature completely? Maybe having shorter text modules for hints like "Schicken Sie uns gerne auch Fotos." (without the legal stuff) might be valuable as well?

**Comment by FrauCsu** [comment]
Then it needs to be shorter. And different advices (geo locations, photos, attachments). Will discuss and come to you on this

**Comment by drjakob** [comment]
tbd

**Comment by tillprochaska** [comment]
We decided to hide the checkboxes in the form for now, but won’t remove the functionality.
