### ISSUE TITLE
Bounce Message for Voice&Co

### ISSUE THREAD

**Issue by drjakob** [tactilenews/100eyes#172]
As an expert, I would like to be notified if the data I send (voice messages, locations, files) cannot be processed by the recipient.

**Comment by tillprochaska** [comment]
@drjakob @FrauCsu: We need that before the start of 50 survivors as well, right?

**Comment by FrauCsu** [comment]
Yes!

**Comment by tillprochaska** [comment]
@drjakob @FrauCsu Is this still a thing now that we have indicators in the UI? Especially you said you’d like to prevent bounce messages to users if possible…

**Comment by drjakob** [comment]
Yes, but we would like a bounce message for voice. Ideally stating "Bitte sende Sprachnachrichten direkt an den Account von Frau Csuraji [Account einfügen], da unser System sie noch nicht versteht."
