### ISSUE TITLE
Include Footer with license + support

### ISSUE THREAD

**Issue by drjakob** [tactilenews/100eyes#174]
The project should have a footer
"tactile.news Csuraji Vicari Gbr, Große Bäckerstr. 19, 21335 Lüneburg. Entwicklung mit freundlicher Unterstützung des Bundesministeriums für Bildung und Forschung und des Prototypefund Germany. Lizensiert unter MIT-Lizenz."

**Comment by tillprochaska** [comment]
@drjakob @FrauCsu: Could you check if any logos need to be included? Are you sure we do not need to reference BMBF?

**Comment by FrauCsu** [comment]
Yes. BMBF and PF. Can you include? Do you need a png?

**Comment by FrauCsu** [comment]
Updated Footer above
