### ISSUE TITLE
default tel contributors

### ISSUE THREAD

**Issue by FrauCsu** [tactilenews/100eyes#176]

**Comment by tillprochaska** [comment]
@FrauCsu Was ist damit gemeint?

**Comment by FrauCsu** [comment]
Dass wir ein Telefonnummer-Feld brauchen. Bei "Lokalexperten".

Till Prochaska <notifications@github.com> schrieb am Di., 16. Juni 2020,
12:06:

**Comment by tillprochaska** [comment]
Ok, dann schließe ich mal, weil Duplikat von #186 und implementiert in #194.
