### ISSUE TITLE
Indicate if message contains unsupported contents

### ISSUE THREAD

**Issue by drjakob** [tactilenews/100eyes#184]
As editor
I want to see if there are no-text-contents retrieved in log which I can't see in system.

**Comment by tillprochaska** [comment]
@roschaefer: I had a quick look at the Telegram API docs: https://core.telegram.org/bots/api#message

I think it should be fine to flag a message as unsupported, if it contains any of the following properties:

`animation`, `audio `, `document`, `sticker`, `video`, `video_note`, `voice`, `contact`, `dice`, `game`, `poll`, `venue`, `location`, `invoice`, `successful_payment`, `passport_data`.

For email, I think it should be fine to check if the email contains non-photo attachments, right?
