### ISSUE TITLE
info about contributors in database - default settings

### ISSUE THREAD

**Issue by FrauCsu** [tactilenews/100eyes#186]
As an editor
I want to have certain info about my contributors. Default settings should include

- name, family name
- Street and Number 
- Postal Code and City 
- Mobile Phone Number
- room for second phone number (e.g. work)
- Telegram Handle
- preferred eMail Address

**Comment by tillprochaska** [comment]
@FrauCsu: Kann die Adresse ein Textfeld sein?

<img width="879" alt="Screenshot 2020-06-11 21 02 43" src="https://user-images.githubusercontent.com/1512805/84428551-f0fbf400-ac26-11ea-8333-0ec3cae019b5.png">

**Comment by FrauCsu** [comment]
Hallo Till,
ich frage mich gerade, ob es die Möglichkeit geben kann, direkt aus
100eyes Daten in Tabellenform zu bekommen? Use case: Ich bin
Datenjournalist und möchte zeigen, woher unsere 50survivors kommen. Im
Idealfall könnte ich die Informationen (PLZ) als Datenpunkte aus
unserem System bekommen. Kriegen wir sowas hin? Allein bei
50survivors fallen mir mehrere Anwendungen ein, wo ich aus Personendaten
oder den Antworten der Leute gerne Daten im Tabellenformat speichern wollen
würde. Wäre natülrich toll, das ginge. Ohne dass ich die PLZs zB alle
händisch abschreiben und in eine Tabelle eintragen muss. Was sagst du?
Kann es als issue (ohne Milestone) anlegen.
So oder so erscheint es mir sinnvoll, von Anfang an Straße, Hausnummer, PLZ
und Ort getrennt zu erfassen. Zu kompliziert?

**Comment by tillprochaska** [comment]
> ich frage mich gerade, ob es die Möglichkeit geben kann, direkt aus
100eyes Daten in Tabellenform zu bekommen?

Ja, das geht definitiv und auch relativ leicht, ich habe #190 erstellt.

> So oder so erscheint es mir sinnvoll, von Anfang an Straße, Hausnummer, PLZ
und Ort getrennt zu erfassen. Zu kompliziert?

Ja, das stimmt in jedem Fall. Es ist ein bisschen mehr Aufwand, das UI trotzdem übersichtlich zu halten, aber das sollte es wert sein.

**Comment by FrauCsu** [comment]
Sehr gut!


Astrid Csuraji

Post: Auf dem Meere 10 | D-21335 Lüneburg
Taschenbüro: +49 163 40 29 332
www.csuraji.de <http://www.torial.com/astrid.csuraji>
