### ISSUE TITLE
[improvement] Improve conversations create message flow

### ISSUE THREAD

**Issue by mattwr18** [tactilenews/100eyes#1896]
```
As a user of the conversations flow
I would like to scroll have a better UX when creating a new message in the conversation
So that I don't need a full refresh and scroll all the way to the bottom to create a new message
```

**Comment by soey** [comment]
As the user requested we will flip the order of messages to have the latest on top and add the input field on top as well.
With that the user don't have to scroll down anymore to get to the latest conversation and can directly respond from the top of the screen.
