### ISSUE TITLE
Export contributors as CSV/Excel

### ISSUE THREAD

**Issue by tillprochaska** [tactilenews/100eyes#190]
See #186

Hallo Till,
ich frage mich gerade, ob es die Möglichkeit geben kann, direkt aus
100eyes Daten in Tabellenform zu bekommen? Use case: Ich bin
Datenjournalist und möchte zeigen, woher unsere 50survivors kommen. Im
Idealfall könnte ich die Informationen (PLZ) als Datenpunkte aus
unserem System bekommen. Kriegen wir sowas hin? Allein bei
50survivors fallen mir mehrere Anwendungen ein, wo ich aus Personendaten
oder den Antworten der Leute gerne Daten im Tabellenformat speichern wollen
würde. Wäre natürlich toll, das ginge. Ohne dass ich die PLZs zB alle
händisch abschreiben und in eine Tabelle eintragen muss. Was sagst du?
Kann es als issue (ohne Milestone) anlegen.
Bitte PLZ und Ort getrennt erfassen

**Comment by roschaefer** [comment]
Here is a one-liner to generate a CSV file in `bin/rails c`:

```ruby
 CSV.open("myfile.csv", "w") {|csv| (User.pluck(:city, :zip_code).each {|row| csv << row }) }
```

Can we close this?

By the way, none of the users has a city or a zip_code so far.

**Comment by tillprochaska** [comment]
> Can we close this?

Don’t think so – we should have a UI for this (e.g. a simple secondary button next to the create user button), as this is likely something editors should be able to do theirselves.

**Comment by tillprochaska** [comment]
Closed in #1333.
