### ISSUE TITLE
Trim organizations model

### ISSUE THREAD

**Issue by mattwr18** [tactilenews/100eyes#1947]
### Dev Notes

We need to trim the attributes/models/tables that no longer make sense with multi-tenancy.

- [ ] Individual organizations will not have their own business plans and everything related to them.
       Open question: Do we maintain BusinessPlan model/table? Will the Enterprise have a plan that can be upgraded, for example?

- [ ] Will the organizations still have a contact person? Presumably yes
- [ ] remove 360dialog attrs which are shared between organizations, for example three_sixty_dialog_partner_id, three_sixty_dialog_partner_username, three_sixty_dialog_partner_password,

**Comment by soey** [comment]
My assumptions:
- If the current business plan does not bring any value then drop it in one MR to possibly bring it back later whenever needed
