### ISSUE TITLE
Ensure organization_id set on production DBs

### ISSUE THREAD

**Issue by soey** [tactilenews/100eyes#1978]
I got a url generation error locally cause my seeded requests did not have an organization_id so there was a missing constraints organization_id. This is to be expected, of course, but I think it would be worth making a sanity check on production instances. We ran the **AddOrganizationIdToRequests** data migration so there should not be any, but it would be nice to double check.

_Originally posted by @mattwr18 in https://github.com/tactilenews/100eyes/pull/1951#pullrequestreview-2244619239_

**Comment by mattwr18** [comment]
I just ssh'd in to all production instances and checked this and all requests have an organization id
