### ISSUE TITLE
[Chore] Decide what to display on About page

### ISSUE THREAD

**Issue by mattwr18** [tactilenews/100eyes#1989]
@soey instead of writing comments in our application code, I've created an issue to decide what to display on the about page.

@drjakob @FrauCsu Maybe you have some ideas. At the moment, we have the email from address, Telegram bot username, Threema identity, and signal phone number. We have not kept this page up to date with the WhatsApp phone number, for example. We also display some info on the GitHub commit hash.

**Comment by soey** [comment]
https://github.com/tactilenews/100eyes/pull/2009
