### ISSUE TITLE
rename "Lokalexperten" in produktiv instanz

### ISSUE THREAD

**Issue by FrauCsu** [tactilenews/100eyes#214]
In Produktivinstanz #50survivors
the contributors should be renamed as
"50survivors" instead of
"Lokalexperten"

**Comment by roschaefer** [comment]
What about "Survivors"? Oder "Überlebende"?

**Comment by roschaefer** [comment]
In #264 it's now called "Mitglieder".

**Comment by tillprochaska** [comment]
@roschaefer @FrauCsu I think this isn’t necessary anymore as we now call them "Community" and "Mitglieder", right?

**Comment by drjakob** [comment]
Yes.
