### ISSUE TITLE
Answers by Users will be dropped if the user has never received a request

### ISSUE THREAD

**Issue by roschaefer** [tactilenews/100eyes#215]
Right now, we're onboarding new users. If a user has never received an initial question, then any messages to the Telegram Bot and any Email to Sendgrid will be silently dropped.

**Expected Behaviour**:
No message should be dropped. 
Either:
* The user gets a feedback: "Wait for us ...."
* Or a message will be saved to the most recent request, even if the user actually has never seen the request.

**Comment by drjakob** [comment]
I opt for: Message will be saved
