### ISSUE TITLE
Strip HTML from emails

### ISSUE THREAD

**Issue by tillprochaska** [tactilenews/100eyes#229]
Some messages contain HTML markup. Most email clients will send both, an HTML and a plaintext variant (even if you compose the email as HTML). I’d guess (but haven’t verified it) that in these cases, the email didn’t include a plaintext variant. If that’s the case, all we can do is to strip HTML markup.

A few different edge cases: 
* /requests/3#message-193
* /requests/2#message-90
* /requests/5#message-375
* /requests/5#message-379
* /requests/5#message-420

**Comment by drjakob** [comment]
Test github ruby gem?

**Comment by drjakob** [comment]
On the fly? (Robert)

**Comment by FrauCsu** [comment]
> Nicht on the fly

Warum nicht? fragt Robert. Gibt's Gründe.

**Comment by tillprochaska** [comment]
Wenn ich mich korrekt erinnere, haben wir das gemeinsam mit #228 besprochen. Einfach nur HTML-Markup zu entfernen ist vermutlich nicht allzu aufwändig. Aber wenn's dann darum geht, Signaturen, Zitate etc. zu entfernen, sollten wir darauf achten, dass das auch noch flott geht, wenn wir das in einem View für 50+ Nachrichten machen.

Grundsätzlich war die Überlegung: Warum sollten wir es jedes Mal machen, wenn wir eine Nachricht anzeigen, wenn wir diese ganzen Säuberungsschritte auch ein einziges Mal machen können, wenn wir die Nachricht empfangen.
