### ISSUE TITLE
problem with provider-blocklists

### ISSUE THREAD

**Issue by drjakob** [tactilenews/100eyes#234]
3 of 50 experts can't receive our emails because  our mailservice Sendgrid is on receivers-providers-blocklist: "Your Internet service provider since part of their network is on our block list"
Outlook, Hotmail
Possible solutions:
* They add us to their adress books (probably won’t solve the problem, as messages are blocked based on IP address, even before sender address is evaluated)
* move sending to uberspace (might introduce new problems)
* use a different Sendgrid plan and hope, the IP address range changes

**Comment by tillprochaska** [comment]
@FrauCsu Did you manage to upgrade the Sendgrid plan?

**Comment by FrauCsu** [comment]
Noch nicht. Warte auf Kreditkarte. Diese Woche on my list.


Astrid Csuraji

Post: Auf dem Meere 10 | D-21335 Lüneburg
Taschenbüro: +49 163 40 29 332
www.csuraji.de <http://www.torial.com/astrid.csuraji>
