### ISSUE TITLE
Intro 4 Steps

### ISSUE THREAD

**Issue by drjakob** [tactilenews/100eyes#248]
On the landing page there should be 4 steps how to use the tool:
1. Stelle 50 Menschen eine Frage mit einem Klick
2. Menschen antworten auf ihrem favorisierten Kanal
3. Werte die Antworten aus
4. Komponiere deine Veröffentlichung

**Comment by drjakob** [comment]
<img width="1081" alt="Bildschirmfoto 2020-07-08 um 22 45 50" src="https://user-images.githubusercontent.com/11591426/86968696-e4f34b80-c16c-11ea-9aa6-66d6ba2e5265.png">
https://www.crowdfarming.com/en

**Comment by drjakob** [comment]
Like this

**Comment by tillprochaska** [comment]
@drjakob: Would you be happy with smth like this?

<img width="980" alt="Bildschirmfoto 2020-08-18 um 18 58 33" src="https://user-images.githubusercontent.com/1512805/90542727-d729e080-e184-11ea-88c6-01f66513abc3.png">
