### ISSUE TITLE
Conversation-Link to most recent Request

### ISSUE THREAD

**Issue by roschaefer** [tactilenews/100eyes#265]
```gherkin
Feature: Conversation-Link to most recent Request
  As a journalist
  I want to be able to send direct messages to individual users
  e.g. in order to get consensus for quotes
```

Hint: It should be enough for now to add a link to the conversation of the most recent request. The link can be added on the user profile. If in fact the actual message is about a previous request (content-wise), this needs to be manually assigned by the journalist. Same problem as in #210 #235 #57 

![Screenshot - 2020-06-24T174821 623](https://user-images.githubusercontent.com/2110676/85587824-68c41880-b642-11ea-865b-cc9ab2dd5e5b.png)

**Comment by tillprochaska** [comment]
@drjakob: What are the aspects still up for discussion?

**Comment by drjakob** [comment]
We think there is anozher solution sketched in figma. Isn't it?

**Comment by tillprochaska** [comment]
I think the most straight-forward, short-term solution would be to simply adjust the link target of this button:

<img width="862" alt="Bildschirmfoto 2020-06-29 um 17 09 56" src="https://user-images.githubusercontent.com/1512805/86023064-79ea9c00-ba2b-11ea-8eea-e71a80c600b3.png">
