### ISSUE TITLE
BUG Truncate Names

### ISSUE THREAD

**Issue by drjakob** [tactilenews/100eyes#266]
The name of community members is shortened to two parts. For example: "Erika von Mustermann" becomes "Erika von". This is not a desired behavior, since names can consist of more than two components (double names, titles of nobility, non-German names). For me its a bug, not a feature.

**Comment by tillprochaska** [comment]
Yes, definitely, this should have never landed in the codebase:

https://github.com/tactilenews/100eyes/blob/master/app/models/user.rb#L31-L39

We should simply add separate inputs for first and last name.
