### ISSUE TITLE
alternating colors in letter avatars

### ISSUE THREAD

**Issue by drjakob** [tactilenews/100eyes#271]
As editor I would like
alternating colors in letter avatars in order
to easily identify community-members in the subconscious.
I would like colors starting with
 #0080FF
 #00FE00
 #FF00A0
 #FAE742
 #323232

**Comment by tillprochaska** [comment]
Closed in #270 

<img width="864" alt="Bildschirmfoto 2020-07-07 um 16 46 29" src="https://user-images.githubusercontent.com/1512805/86798788-78475680-c071-11ea-81fb-f0aa0948f69c.png">
