### ISSUE TITLE
Onboarding Wizard for Contributors

### ISSUE THREAD

**Issue by smalbroc** [tactilenews/100eyes#380]
As contributor
I want to be guided through the onboarding process step by step
in order not to be overwhelmed with information about different channels I don't use via mail
e.g. welcome! you can use telegram, fb, mail, this is how you use telegram, this is how you use mail, this is how you use fb. 

better: 
step 1: Welcome, this is our process
step 2: What is your name? Which channel would you like to use?
step 3: This is how you use telegramORmailORfacebook
etc.

![IMG_20200923_175902](https://user-images.githubusercontent.com/38259090/94040503-54222880-fdc9-11ea-943b-8489d15afc89.jpg)

**Comment by drjakob** [comment]
So what will happen with name information

**Comment by tillprochaska** [comment]
@smalbroc @drjakob @FrauCsu How about having the photos of the journalists doing the project above or below the intro text? For example, for #50survivors, we could have the photos of Astrid, Jakob, Isa and Bertram on the page to add a more welcoming, personal touch to the on boarding process. Also, this might break up the page visually, as the onboarding text/intro is quite long.

**Comment by smalbroc** [comment]
I like the idea of having photos after the introduction of WHO is doing the research. It’s great to know a face, when you are having a dialogue with someone over weeks. 

However, the photos shouldn’t be too big in order not to interrupt the onboarding.

 

Von: Till Prochaska <notifications@github.com>
Antworten an: tactilenews/100eyes <reply@reply.github.com>
Datum: Donnerstag, 24. September 2020 um 20:38
An: tactilenews/100eyes <100eyes@noreply.github.com>
Cc: smalbroc <annabell.brockhues@gmail.com>, Mention <mention@noreply.github.com>
Betreff: Re: [tactilenews/100eyes] Onboarding Wizard for Contributors (#380)

 

@smalbroc @drjakob @FrauCsu How about having the photos of the journalists doing the project above or below the intro text? For example, for #50survivors, we could have the photos of Astrid, Jakob, Isa and Bertram on the page to add a more welcoming, personal touch to the on boarding process. Also, this might break up the page visually, as the onboarding text/intro is quite long.

**Comment by FrauCsu** [comment]
Pictures from the editors are necessary, if editors want to ask the contributors to send their photos as well.
We already have an issue for that.
