### ISSUE TITLE
Finnish localisation of onboarding views

### ISSUE THREAD

**Issue by tillprochaska** [tactilenews/100eyes#424]

**Comment by tillprochaska** [comment]
@drjakob Just did a quick evaluation, adding new translations should be pretty straight forward. However, as soon as we add the settings page, we’d need it to handle translations as well.

As this might make things more complicated and I could imagine #Schweinesystem might be an exception (in terms of having contributors that speak different languages), it might be sensible to

* develop the new settings page without multi-language capabilities (i.e. you would only be able to manage onboarding content in a single language)
* keep the current system (i.e. manage contents manually) for #Schweinesystem, as this works with multiple languages out of the box.

(Though that totally depends on wether you expect more projects to require multi-language capabilities in the near future.)

![localhost_3000_onboarding_token=abc123 locale=fi(iPhone 6_7_8)](https://user-images.githubusercontent.com/1512805/95770419-aa440680-0cb9-11eb-9bd0-fc9f799bba9c.png)

**Comment by tillprochaska** [comment]
Oder um es noch mal anders zu formulieren: Es ist quasi kein Aufwand, Finnisch im aktuellen Zustand hinzuzufügen. Sobald wir die Settings haben geht das nicht mehr.

Aber es besteht ja eine gute Chance, dass die Settings erst fertig werden, nachdem das Onbiarding für die Schweine zum großen Teil fertig ist.

**Comment by drjakob** [comment]
Perfekt. Wenn Multilanguage das beste Feature aller Zeiten ist lassen wir uns was einfallen.

**Comment by drjakob** [comment]
Whats missing here @tillprochaska ?

**Comment by tillprochaska** [comment]
@drjakob There are still a few translations missing. Apart from that, it’s ready and Robert already approved the changes:

https://github.com/tactilenews/100eyes/pull/429
