### ISSUE TITLE
Avoid unknown users in Telegram

### ISSUE THREAD

**Issue by FrauCsu** [tactilenews/100eyes#425]
As editor
I do not want ppl to share our telegram bot name
so we do not have unknown users in our community.

**Comment by FrauCsu** [comment]
How do we avoid this? Is there any way of asking for login credentials?

**Comment by tillprochaska** [comment]
From Slack:

> Da Nutzer uns (mit der aktuellen Telegram-Integration) momentan immer zuerst anschreiben müssen, bevor wir mit ihnen interagieren können, muss das grundsätzlich erstmal für alle offen sein. (Andernfalls könnte sich gar niemand mehr mit dem Bot anmelden – das geht ja auch nicht.) Es gibt aber natürlich Optionen, das einfacher/besser zu machen:
> 
> Die erste wäre es, wie schon häufiger vorgeschlagen, das Anmeldeverfahren für den Bot umzustellen und den “Login mit Telegram”-Button in unserem Onboarding-Flow zu verwenden. (Das haben wir mittelfristig ja so oder so vor, weil es die Anmeldung auch für Nutzer einfacher macht.) Wir könnten dann sicherstellen, dass nur Personen den Bot verwenden können, die sich über unseren Onboarding-Flow angemeldet haben.
>
> * Ein kurzfristige, möglicherweise einfacher zu implementierende Lösung: Nutzer, die sich über den Telegram-Bot anmelden, sind nicht direkt aktiv. Sie würden dann in einer separaten Liste angezeigt werden und ihr könntet sie einzeln überprüfen und bestätigen oder löschen.
> 
> * Beide Lösungen schließen sich gegenseitig auch nicht aus. Auch mit dem neuen Onboarding-Flow könnte es (wie du ja bereits angemerkt hast), dazu kommen, dass die falschen Personen den Onboarding-Link in die Finger bekommen und sich anmelden. Es könnte also auch für E-Mail-Nutzer sinnvoll sein, dass diese erst durch euch bestätigt werden müssen.

**Comment by drjakob** [comment]
Ich denke das ist zu viel Komplexitätß

**Comment by FrauCsu** [comment]
Complex? Maybe, but more secure as well. Let's do this: quickly deploy our onboarding wizard and set all ppl to inactive as default. Activate users manually. @drjakob

**Comment by tillprochaska** [comment]
@FrauCsu @drjakob Can we close this issue in favour of #426 and #427? Once users can only sign up using a single-use invite link, we won’t have this problem anymore, right?

**Comment by FrauCsu** [comment]
Yes, @tillprochaska
