### ISSUE TITLE
Display/Download raw message data from UI

### ISSUE THREAD

**Issue by tillprochaska** [tactilenews/100eyes#462]
We should have an option to show or download the raw message data for messages, similar to how most email clients allow you to open the raw email message. Right now, the only way to access raw message data is to ssh into the server, find the message record using the Rails console, copy and paste the raw data or download the message via scp or a similar tool. That takes quite a lot of time, can be down *only*  by devs and is error-prone.

<img width="227" alt="Screenshot 2021-02-01 at 14 47 57" src="https://user-images.githubusercontent.com/1512805/106467142-8ab92f80-649c-11eb-9e69-62a5745ad4ad.png">

I think there are at least two use cases for this:

**1) Deciding wether unsupported contents are important, recovering unsupported contents**
We’ve had quite a few situations where actual contributors sent us emails containing unsupported contents. In many of those cases, the reasons for the "unsupported content" warning probably is caused by attached images in email signatures (e.g. company logos), contact cards (e.g. vcf files), email signatures (e.g. p7s) files.

However, in some cases, the attached files might actually be relevant to the message. While ideally 100eyes should support receiving any email attachment, for know it would already help if it was possible to open/download the raw message data. This would allow us to quickly evaluate what a problem with a message is and, if necessary, to decode the attachment from the raw email.

**2) Recovering parts of messages that have been incorrectly stripped out**
As email clients format HTML emails in lots of different ways, it happens from time to time that the logic that removes all HTML markup incorrectly also removes parts of the actual message content. In those cases, even tech-savvy editors could use that feature to quickly see the actual message contents.

**Comment by tillprochaska** [comment]
As we now have an admin dashboard, I'd suggest adding this to the dashboard instead of the main application. Apart from that, there is still a need to download the raw message data to easily debug/retrieve messages that contain unsupported content types and/or use unsupported messenger features.

**Comment by FrauCsu** [comment]
Yes, please.
