### ISSUE TITLE
Feedback after sending question

### ISSUE THREAD

**Issue by drjakob** [tactilenews/100eyes#47]
As an editor
I want to receive a Feedback "Sent successfull" after sending out a question to my community
in order to avoid sending duplicates.

**Comment by tillprochaska** [comment]
@drjakob @FrauCsu: Currently exploring different options, feedback welcome. I think I prefer variant 2.

**Variant 1:**
<img width="934" alt="Screenshot 2020-05-21 15 12 18" src="https://user-images.githubusercontent.com/1512805/82563430-5c4a2d00-9b77-11ea-93ff-180254fa1fb0.png">

**Variant 2:**
<img width="934" alt="Screenshot 2020-05-21 15 13 20" src="https://user-images.githubusercontent.com/1512805/82563647-b519c580-9b77-11ea-915d-6fdbd5f14882.png">


**Variant 3:**
![2020-05-21 15 24 21](https://user-images.githubusercontent.com/1512805/82563540-8f8cbc00-9b77-11ea-9ee6-4aed14073ed5.gif)

**Comment by FrauCsu** [comment]
Variante 2

**Comment by FrauCsu** [comment]
(Jakob likes 3, but I find it not very intuitive.)
