### ISSUE TITLE
Add telegram handle in 100eyes

### ISSUE THREAD

**Issue by drjakob** [tactilenews/100eyes#54]
```gherkin
Feature: Auto-update telegram username
  As a user
  I want my user record in the database to be updated when I send a message to 100eyes via Telegram
  Because I want to change my telegram account name and the cached account name in the database must be updated accordingly

```

**Comment by roschaefer** [comment]
The telegram ID in our database *must match* the telegram id of the telegram user account. It is not wise to change the ID through the Web UI. Instead, everytime a user sends a message, we could update the user account with a potentially updated username. All telegram accounts have another, numeric ID, which seems to be immutable and we can distinguish user accounts via this numeric ID.

**Comment by roschaefer** [comment]
I'm going to edit this issue description..

**Comment by drjakob** [comment]
BUT How to add a telegram user as 100eyes user (Lokalexperte) via interface?

**Comment by roschaefer** [comment]
It's not possible. You must initiate the conversation as the user.

**Comment by drjakob** [comment]
BUT I want to create all my users in interface. The self-creation via telegram is spooky (at least).

**Comment by drjakob** [comment]
No problem with double-opt-in. But CREATE has to be something different.

**Comment by roschaefer** [comment]
We will implement a way to create users manually, for E-Mail alone it's necessary. But we will not make the telegram username editable. If you want to have a user through Telegram, you must ask her/him.

@drjakob you can see the initial message of the bot when you send `/start` as a message to the Telegram bot. Right now it's saying `"Hello #{username}". Could you create a nice German explanation to ask the user to send an answer back to the bot?

**Comment by drjakob** [comment]
"Hallo, schön, dass du an [PROJEKTNAME]* teilnimmst. Ich bin der Bot der Dialogsoftware 100eyes. Ich freue mich auf den Dialog mit dir. Bitte antworte mit kurz mit "Hallo" auf diese Nachricht, damit ich weiß, dass ich dir auf diesem Weg Nachrichten schicken darf."
Is it possible to fill [PROJEKTNAME] via 100UX? otherwise should be #50survivors
