### ISSUE TITLE
Show alternatives when no telegram name

### ISSUE THREAD

**Issue by drjakob** [tactilenews/100eyes#55]
![3DE1962D-100F-44AD-9365-B3468E6E5DDD](https://user-images.githubusercontent.com/11591426/82190033-acfc2480-98f0-11ea-9092-046984744fce.jpeg)
As editor
I want so see the telegram connection also If user has not defined a telegram name
In order so see the activity.

Explanation: many users don’t habe defined a telegram name.

**Comment by roschaefer** [comment]
There is no way to see a "telegram connection". @drjakob can you clarify this issue?

**Comment by drjakob** [comment]
IF username present –> show "username (using Telegram)"
ELSE IF show "(using Telegram)"
