### ISSUE TITLE
Ask for additional information In threads (verlauf)

### ISSUE THREAD

**Issue by drjakob** [tactilenews/100eyes#60]
As editor
I want to habe the possibility to ask lokalexperten for infos in a thread (Verlauf)  with an individual expert (Lokalexperte)
In order to get the full picture for my reporting.
![7D5AA41C-67AF-4C41-932F-B23E19FCB679](https://user-images.githubusercontent.com/11591426/82298581-9ddeaa80-99b4-11ea-9888-0661487529eb.jpeg)

**Comment by FrauCsu** [comment]
@drjakob Was ist mit diesem Issue, noch relevant für 50s?
