### ISSUE TITLE
Issues with password reset links opened via Gmail web

### ISSUE THREAD

**Issue by tillprochaska** [tactilenews/100eyes#652]
cGmail replaces links in email with what they call "secure redirects", which basically means they will replace a URL like `https://example.org` with

```
https://www.google.com/url?q=https://example.org&source=gmail&ust=1611828026233000&usg=TOKEN
``` 

where `ust` is a timestamp 24 hours in the future and `usg` probably is some kind of hash/signature so you can’t just use Google’s redirect service for arbitrary URLs. (But these params aren’t really relevant to the problem.)

When you click the link, this is the request chain you’ll get:

```
1) GET 302 https://www.google.com/url?q=https://100eyes.test/users/1/password/edit?token=abc123
2) GET 302 https://100eyes.test/users/1/password/edit?token=abc123
3) GET 200 https://100eyes.test/users/1/password/new
```

For some users, in step 3) the form to request a reset link will be rendered and a flash message indicating the URL was invalid is displayed. I’ve been able to reproduce this in Firefox 85.0b9 and 14.0.1 (but couldn’t do so in Chrome 88.0.4324.96), so here’s some insight:

* The redirect from step 2) to 3) is [Clearance’s default behavior](https://github.com/thoughtbot/clearance/blob/master/app/controllers/clearance/passwords_controller.rb#L24). It’ll save the confirmation token to the session, then redirect you to the edit page without the token. ([This commit explains](https://github.com/thoughtbot/clearance/commit/ad294a94e626b0f2ae29cd74f733c979acc9c7ac) why they do this.)

* Step 3) will then get the token from the session and – if the token is set/valid – actually shows the password reset form. If the token isn’t set/valid, it’ll just render the request password form again.

* The problem seems to be that some browsers do not include cookies in request 3), and as the session id is stored in a cookie, and the token is stored in the session, the token isn’t set when Clearance tries to validate it in step 3).

* This is related to the `SameSite` cookie policy being set to `strict` (which we probably we shouldn’t change). In Firefox, and probably other browser too, cookies won’t be sent if the initial request in a request chain was a third party. That’s why the session cookie is dropped when you click on the Gmail link.

* This also means that everything will work just fine if you open the link directly (without being redirected by Google). As a general workaround/solution to this problem, I’d recommend we include the password reset URL in the email, e.g. like this:
  
  > [Mein Passwort ändern](#)
  > Falls dieser Link nicht funktioniert, kopiere die folgenden Adresse und öffne sie in deinem Browser: https://100eyes.test/users/...
  
  This is a somewhat standard practice anyways, probably for reasons like this.

* This [ticket on Mozilla’s Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1465402) has some more info and also references [a simple example to reproduce this](https://cookie-lab-app.vercel.app).

**Comment by FrauCsu** [comment]
This problem is not fixed yet. We had ppl (not Gmail users) who tried to onboard for the first time as editors and got send into loops instead of a quick change of password. Who can fix this? @tillprochaska @roschaefer ?

**Comment by mattwr18** [comment]
@FrauCsu this was never an issue with just Gmail users, it's an issue with being referred from an email client, other site. It's difficult to say what went wrong for the clients since we weren't watching to see if they clicked the link, or copied and pasted the link into a browser tab. I guess it was the former, but it's impossible to tell.

We discussed in a past sprint about changing the cookie policy, and agreed it would be alright. If that is still the case, I could quickly do it, if you want.
