### ISSUE TITLE
Add support for Threema::Receive::DeliveryReceipt

### ISSUE THREAD

**Issue by mattwr18** [tactilenews/100eyes#708]
```
As a contributor
I would like to be able to respond with a thumbs up/down
Since sometimes I want to acknowledge I read, but don't have an words to add
```

```
As an editor
I would like encourage responses, even if they are non-verbal
So that I can have a better idea of the engagement of my request/campaign.
```

**Comment by mattwr18** [comment]
Re-reading this, I have questions. I think it would be nice to be able to handle user reactions, but only Signal and Threema provide these, so it would be kind of channel specific. Also, with delivery receipts, I think this is channel specific, and seems to be only for Threema, so it would be potentially confusing to show some UI that indicates a message was received by a contributor it it were only for Threema.

I think we can close this issue, to be honest.

**Comment by FrauCsu** [comment]
Then let's close this
