### ISSUE TITLE
GDPR Compliance

### ISSUE THREAD

**Issue by tillprochaska** [tactilenews/100eyes#771]
Let’s use this ticket to compile all the information we think is relevant regarding GDPR compliance. I’ve marked aspects I think might be critical/violations with a 💥, but the absence of that emoji obviously doesn’t mean that something is uncritical, and I’m not a lawyer. ;)

### Services we’re using
* **Digital Ocean**
   Servers and databases
   Server location: Frankfurt, DE

* **Postmark**
   Inbound and outbound emails
   Server location: US ([source](https://postmarkapp.com/eu-privacy#security-and-privacy))

* **Telegram**
   Delivering and receiving Telegram messages
   Server location: ?

* **Threema**
   Delivering and receiving Threema messages
   Server location: ?

* **Cloudflare**
   DNS hosting, content delivery network (CDN), DDoS protection and application firewall
   Server location: many locations around the world ([source](https://www.cloudflare.com/en-gb/network/)

* **Sentry**
   Error monitoring
   Server location: ?

* **Gmail**
   Europa
   Support email address (support@tactile.news???)

* **Slack**
   Team communication, sharing bug reports, potentially including contributor data

* (**GitHub**)
  I don’t think we have any contributor PII in GitHub, but we should make sure this is actually the case.

* (**PingPing.io**)
   Uptime monitoring, doesn’t process PII
   Server locations: multiple locations around the world
 
* (**inwx.de**)
  Domain registrar, doesn’t process PII

### DPAs already signed
@FrauCsu @drjakob Could you double check for which services you already signed a DPA?

[This list](https://github.com/tollwerk/data-processing-agreements) compiles information about GDPR compliance/availability of DPAs of many services (including some of the services we’re using) 

- [ ] Telegram (I don’t think Telegram offers a DPA)
- [ ] Threema (They seem to offer that for their Threema Work product, but I couldn’t find any info for Threema Gateway. Probably best to contact support.)
- [x] Digital Ocean (supports signing a DPA)
- [x] Postmark (supports signing a DPA)
- [x] Cloudflare (supports signing a DPA)
- [x] Sentry (supports signing a DPA)
- [x] Gmail
- [x] Slack
- [x] netcup
- [ ] Voiceflow

### How we’re securing access to these services:
- Digital Ocean: 2FA enforced for all accounts (please check!)
- Postmark: all team members have 2FA enabled, no way to enforce
- Telegram: bots tied to personal Telegram account, no idea who manages them
- Threema Gateway: shared account, no 2FA
- Cloudflare: 2FA enforced for all accounts (please check!)
- Sentry: ?
- Gmail: ?

### How contributors give consent:
- 💥 We don’t have a privacy policy.
- 💥 New contributors currently are *not* informed about how we use their data and are not asked for consent.
- 💥 Currently, we do not use double opt-in for email and Threema.

### Logging
- 💥 I think we log every single request, possibly including the full non-anonymised IP address (which is PII).

### Cookies
* Rails session cookie
* Clearance remember token: We use that cookie to keep editors logged in, so they don’t need to type in their credentials every time they open 100eyes.
* Cloudflare UID cookie: This cookie is set by Cloudflare (see [Cloudflare docs](https://support.cloudflare.com/hc/en-us/articles/200170156-Understanding-the-Cloudflare-Cookies))

### Threema
* We’re using E2E encryption to receive messages via Threema. Encryption is terminated at our servers, not at editor’s devices. (See this [comment](https://github.com/tactilenews/100eyes/issues/691#issuecomment-775027960))

### Who has access to the data we store:
* Everyone on the developer team
* Everyone with an editor account
* 💥 We do not log/audit if/when developers access contributor data.

**Comment by FrauCsu** [comment]
> Any News from Threema, @drjakob ?

Definitely no AVV from Threema, @drjakob ? Then we take it off the list.

**Comment by FrauCsu** [comment]
> contacted telegram via @gdprbot

If there is no AVV here either, we can take Telegram off the list, too @drjakob

**Comment by drjakob** [comment]
yay
