### ISSUE TITLE
Community-Metrics

### ISSUE THREAD

**Issue by drjakob** [tactilenews/100eyes#778]
As an editor, I want community metrics at a glance: 

- [ ] Speed of response
- [ ] best-responding community members
- [ ] total number of responses to research
- [ ]  most important tags
- [ ] most successful questions
- [ ] From this, a 100-KPI score should be calculated to have a target value for projects.

**Comment by mattwr18** [comment]
When do we consider this as completed? We have merged, not yet deployed, the basic community metrics section in the dashboard, but it does not include all these metrics. We have a PR for a heatmap, but it's not clear to me if we still want all of these metrics and where they would live.

Maybe having smaller issues that are clear when they can be closed would be better? We could still keep a tracking issue that can be closed once all the individual issues are closed.

**Comment by drjakob** [comment]
Please leave this open, I still like my ideas.

**Comment by mattwr18** [comment]
I was not insinuating that the ideas were not good, I was asking for us to make it clear when we can close it, ie after implementing some or all of the ideas.

I like that you turned the specifics metrics into a checklist, I think that is a step forward in clarity. Can we also create individual issues for each, which make it clear what the benefit of the metric is and where we would put it?

**Comment by mattwr18** [comment]
@drjakob @FrauCsu Can we make a decision on my proposal for this ticket?

**Comment by mattwr18** [comment]
Moving this to a future quarter as there are still open questions :point_up:

**Comment by drjakob** [comment]
Simple Metric: 100% is community-size = count messages last week
So e.g. community size= 50 contributors, 50 messages last week = 100%
40 messages last week = 80% activity,
but: 55 messages last week = 100% (not more)
