### ISSUE TITLE
Integrate Checkbox Datenschutzerklärung in Onboarding

### ISSUE THREAD

**Issue by drjakob** [tactilenews/100eyes#822]
As a user
I want to accept the Datenschutzerklärung on Onboarding-Site with a mandatory checkboy (default: not checked).
"Ich habe die Allgemeine Nutzungsbedingungen 100eyes [LINK] und die Datenschutzerklärung [LINK] zur Kenntnis genommen und bin mit deren Geltung einverstanden. In unserer Datenschutzerklärung ist erklärt, welche Tools wir nutzen und mit welchen Firmen wir zusammenarbeiten. Diese Partner speichern und übertragen je nach Nutzung auch Daten in Länder außerhalb der Europäischen Union."

Link zu Datenschutzerklärung: https://tactile.news/100-eyesdatenschutz-verbraucherinnen/ 
Link zu AGB: https://tactile.news/100eyes-agb-verbraucherinnen/ (bearbeitet)

**Comment by tillprochaska** [comment]
@drjakob This might be relevant: Do we need to store the date/time when a contributor gave their consent?

**Comment by phoeinx** [comment]
I had the same question and as I wanted to start implementing, did a short research. Based on Art. 7 (1) DSGVO that states: 

> (1) Beruht die Verarbeitung auf einer Einwilligung, muss der Verantwortliche nachweisen können, dass die betroffene Person in die Verarbeitung ihrer personenbezogenen Daten eingewilligt hat.

> (deepL based translation)(1) If the processing is based on consent, the responsible party must be able to prove that the data subject has consented to the processing of his or her personal data.

I'll for now work with the assumption that we need to store the date/time. Together with our code base that should be enough to prove that the consent was given right? Or do we need to do something more?

**Comment by drjakob** [comment]
Yes

-- 
Dr. Jakob J. E. Vicari
Freelance Creative Technologist
***@***.***
+49 (0)4131 799 85 61

Reporterpreis 2019, Kategorie Multimedia
Ernst-Schneider-Preis 2018, Innovation

*** NEU: Das Buch ***
Journalismus der Dinge. Strategien für den Journalismus 4.0
Herbert von Halem Verlag. Jetzt bestellen: www.halem-verlag.de/journalismus-der-dinge

**Comment by phoeinx** [comment]
Yes to saving time/date of consent is enough, right?

**Comment by phoeinx** [comment]
And one more question - do you want the checkbox
(a) on the general onboarding page before contributors select their medium of choice? 
<img src="https://user-images.githubusercontent.com/34538290/116293087-c1020480-a796-11eb-9d01-c0cad713d29f.png?s=10" height="300">
 or

(b) on the medium specific sign-up pages? 
<img src="https://user-images.githubusercontent.com/34538290/116293383-1ccc8d80-a797-11eb-9da5-cae18c6a34e8.png?" height="350">

I think (b) makes more sense, this way the nicely working reading flow on the onboarding page doesn't get disturbed and it feels more natural to give your consent to the privacy agreement when you are already filling in your data.

**Comment by tillprochaska** [comment]
+1 for b)
