### ISSUE TITLE
Automated deployment from staging to demo

### ISSUE THREAD

**Issue by FrauCsu** [tactilenews/100eyes#836]
As journos in our dev team 
we need an automated deploment from staging to demo
in order to keep track and to always demonstrate latest version of deployment.

**Comment by tillprochaska** [comment]
@FrauCsu Nur um das klarzustellen: Wir haben ursprünglich mal darüber gesprochen, demo.100ey.es wie jedes andere Produktivsystem auch zu behandeln. Der Grund dafür ist, dass wir eigentlich kurz vor oder während einer eurer Demos keine Änderungen deployen wollen. Das birgt zum einen die Gefahr, dass ein unentdeckter Bug plötzlich während eurer Demo auftaucht. Zum anderen könnten UI-Änderungen etc., die ihr während einer Demo zum ersten Mal seht, ja auch verwirrend sein.

Ich würde deshalb vorschlagen: Wir deployen weiterhin manuell zu demo.100ey.es. Wenn ihr bestimmte neue Features unbedingt auf dem Demo-System benötigt, gebt ihr uns einfach einen Tag vorher Bescheid und wir deployen die Änderungen.
