### ISSUE TITLE
Correct footer Link

### ISSUE THREAD

**Issue by drjakob** [tactilenews/100eyes#843]
The Imprint should be editable in Settings in order to reflect responsibility.

"Realisiert mit 100ey.es, Dialogtechnologie von tactile.news"
[Impressum] 
<img width="673" alt="Bildschirmfoto 2021-05-04 um 01 38 24" src="https://user-images.githubusercontent.com/11591426/116946097-907c0800-ac79-11eb-8978-18531c6c25c3.png">

**Comment by FrauCsu** [comment]
Should we add this now, @drjakob ?
