### ISSUE TITLE
BUG Link Datenschutz (Telegram Onboarding)

### ISSUE THREAD

**Issue by drjakob** [tactilenews/100eyes#895]
Wrong Links: Allgemeine Geschäftsbedingungen should be https://tactile.news/100eyes-agb/
Datenschutz should be: https://tactile.news/100eyes-datenschutz/

**Comment by tillprochaska** [comment]
@drjakob Are you sure the links above are correct this time? Both documents seem to be aimed at newsrooms, not contributors. Also, just to clarify, we’d need to update links for all channels, not only Telegram.

**Comment by drjakob** [comment]
I‘ll check tomorrow. 

-- 
Dr. Jakob J. E. Vicari
Freelance Creative Technologist
***@***.***
+49 (0)4131 799 85 61

Reporterpreis 2019, Kategorie Multimedia
Ernst-Schneider-Preis 2018, Innovation

*** NEU: Das Buch ***
Journalismus der Dinge. Strategien für den Journalismus 4.0
Herbert von Halem Verlag. Jetzt bestellen: www.halem-verlag.de/journalismus-der-dinge
