### ISSUE TITLE
Automatically show Telegram profile pic (re installment)

### ISSUE THREAD

**Issue by FrauCsu** [tactilenews/100eyes#899]
As editor
I want to see the profile picture my contributor uses in telegram 
after she/he/div signs in.

**Comment by FrauCsu** [comment]
Does 100eyes show new profile picture if contributor uploads new one to telegram profile after signing in with 100eyes?

**Comment by roschaefer** [comment]
> Does 100eyes show new profile picture if contributor uploads new one to telegram profile after signing in with 100eyes?

No, the way how it's done in #921 is:
* For any incoming telegram message, does the sender has an `avatar_url` already?
  => If no, try to download the current telegram profile picture
  => If yes, do nothing

This means, we do not refresh new profile pictures as soon as we have downloaded one (old) profile picture. This also means, if a user has no profile picture, our software will try to download it every time someone sends a message.
