### ISSUE TITLE
Automatically show Threema profile picture after signing-in

### ISSUE THREAD

**Issue by FrauCsu** [tactilenews/100eyes#900]
As editor
I want to see the Threema profile picture of a new contributor
after she/he/div has registered in 100eyes.

**Comment by roschaefer** [comment]
> Hi Robert,
> Thanks for your message. Profile pictures are stored solely on enduser devices, and are
> under the authority of the device owner. This is why it is not possible to fetch them with
> Threema Gateway. As users wouldn't know whether their profile picture is fetched or not,
> we prefer to protect user privacy and refrain from providing the mechanism you describe.
> Do you have any further questions we can assist you with?
> Sincerely,
