### ISSUE TITLE
Star good user replies

### ISSUE THREAD

**Issue by drjakob** [tactilenews/100eyes#94]
As a editor
I want to star good user replies 
in order to find the best answers faster.

**Comment by tillprochaska** [comment]
You thought about a single button, right? How about having two options: positive/negative or keep/archive?

That way, editors could have a workflow where new (unrated) messages are always visible, “bad” replies are hidden and “good” replies are easily accessible at a later time, eg when the editor is ready to write the article.

![image](https://user-images.githubusercontent.com/1512805/82576866-81946680-9b8a-11ea-9e44-fc4c2b86df3c.png)

**Comment by drjakob** [comment]
seems smart.  I think its important that our local heroes don't get bad feedback. (Do we get the tigers?)

**Comment by tillprochaska** [comment]
Yes, sure! Contributors shouldn’t and won’t receive a notifications - it’s only meant to organize replies so it’s easy to find only the helpful replies later.

Maybe something like “hilfreich/wenig hilfreich” would be better than a strict good/bad rating.

**Comment by drjakob** [comment]
Or we use color labels like proposed in #159

**Comment by drjakob** [comment]
WE USE A STAR

**Comment by drjakob** [comment]
Just a star
