### ISSUE TITLE
Create dashboard as gateway to 100eyes

### ISSUE THREAD

**Issue by FrauCsu** [tactilenews/100eyes#95]
As an editor I want to have a dashboard
as a gateway to 100eyes

like starting a new topic (RECHERCHE)
like sending a new request (FRAGE STELLEN)
like visiting the users' profiles (LOKALEXPERT*INNEN)

in order to help me navigate through my options.

**Comment by drjakob** [comment]
![Bild von iOS (11)](https://user-images.githubusercontent.com/11591426/82558324-b219d780-9b6d-11ea-9dde-7ec3d7985cf7.jpg)

**Comment by FrauCsu** [comment]
@drjakob Milestone END PF - als nicht-funklionsfähiger Dummy? Oder via framework?

**Comment by mattwr18** [comment]
Is this related to the newly redesigned dashboard that we have started rolling out or is this something separate?
Assuming it is the dashboard that I get when I go to `/dashboard` in our application, when would we consider this issue to be closed?

**Comment by FrauCsu** [comment]
Yes, closed. But can you add the mockup/pic in it for later? Because that dashboard includes more options than we have now. And some interesting thoughts I want to keep for the future @mattwr18

**Comment by mattwr18** [comment]
<img width="428" alt="Bildschirmfoto 2022-09-07 um 09 28 31 (1)" src="https://user-images.githubusercontent.com/26943915/222367403-627592f5-ff92-4a76-9768-fde13330f174.png">
