### ISSUE TITLE
Emojis-on-a-Click

### ISSUE THREAD

**Issue by drjakob** [tactilenews/100eyes#953]
As editor
I want to have some Emojis-on-a-click in order to communicate via messenger while using a desktop-pc.

**Comment by tillprochaska** [comment]
Duplicate of #634

**Comment by tillprochaska** [comment]
Wie wäre es als ersten Schritt mit einem Hinweis auf die Emoji-Picker, die es unter macOS und Windows gibt?

**macOS**
<img width="540" alt="Screen Shot 2021-08-13 at 13 08 30" src="https://user-images.githubusercontent.com/1512805/129348700-b091e003-5db7-422d-ac77-1ca897ef0ba5.png">

**Windows**
<img width="541" alt="Screen Shot 2021-08-13 at 13 09 16" src="https://user-images.githubusercontent.com/1512805/129348704-e6971d59-b2ac-489e-8afb-7208913f30e9.png">

**Comment by FrauCsu** [comment]
> @drjakob Wie wäre es als ersten Schritt mit einem Hinweis auf die Emoji-Picker, die es unter macOS und Windows gibt?
> 
> **macOS**
> <img alt="Screen Shot 2021-08-13 at 13 08 30" width="540" src="https://user-images.githubusercontent.com/1512805/129348700-b091e003-5db7-422d-ac77-1ca897ef0ba5.png">
> 
> **Windows**
> <img alt="Screen Shot 2021-08-13 at 13 09 16" width="541" src="https://user-images.githubusercontent.com/1512805/129348704-e6971d59-b2ac-489e-8afb-7208913f30e9.png">

@tillprochaska I would use "Emojis" instead of "Emoji". Rest looks fine
