### ISSUE TITLE
Add Signal messenger

### ISSUE THREAD

**Issue by roschaefer** [tactilenews/100eyes#958]
```gherkin
Feature: Add Signal messenger
  As a user
  I would like to communicate via Signal private messenger
  For the sake of encryption and to cover more people who use only Signal
```

I did 2 hours of research and I can confirm that it is technically possible to use Signal for our application. It requires an extra service which we need to deploy (+ complexity) and a separate phone number for every instance (+ fees, + rollout time). @drjakob and @FrauCsu told me via phone that they want this feature and are OK with the costs.

Have a look into [this repo](https://github.com/bbernhard/signal-cli-rest-api) and the corresponding [swagger api](https://bbernhard.github.io/signal-cli-rest-api/). 

**Beware** If you [register your phone number](https://bbernhard.github.io/signal-cli-rest-api/#/Devices/post_v1_register__number_) and then [verify your phone number](https://bbernhard.github.io/signal-cli-rest-api/#/Devices/post_v1_register__number__verify__token_) you will loose access to your signal messages from your phone. You can change your device after a period of 7 days only.

1. Download the `docker-compose.yml` from the `README.md`.
2. Run `docker-compose.yml`
3. Check the [Swagger API](https://bbernhard.github.io/signal-cli-rest-api/#/Devices/post_v1_register__number_) and copy the command to verify your phone.
4. If you get `curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number` replace `https` with `http`:
```
curl -X 'POST' 'http://127.0.0.1:8080/v1/register/<phone_number>' -H 'accept: application/json' -H 'Content-Type: application/json'
```
You will see an error message like: 
```
{"error":"Captcha required for verification, use --captcha CAPTCHA\nTo get the token, go to https://signalcaptchas.org/registration/generate.html\nCheck the developer tools (F12) console for a failed redirect to signalcaptcha://\nEverything after signalcaptcha:// is the captcha token.\n"}
```
5. Go to https://signalcaptchas.org/registration/generate.html and solve a captcha. Observe your JavaScript console for the respective token:
![swappy-20210701_213129](https://user-images.githubusercontent.com/2110676/124180879-1a4b2480-dab5-11eb-8026-be0102f0690f.png)
6. Run the command again, this time with captcha:
```
curl -X 'POST' \
   'http://127.0.0.1:8080/v1/register/<phone_number>' \
   -H 'accept: application/json' \
   -H 'Content-Type: application/json' \
   -d '{ "captcha": "<captcha>" }'
```
7. You will receive a text message with your verification code. When you use this code to [verify your phone number](https://bbernhard.github.io/signal-cli-rest-api/#/Devices/post_v1_register__number__verify__token_) you unlink any other device and you are able to receive messages from your service.
8. Enjoy? :thinking:

**Comment by FrauCsu** [comment]
Deadline for first trial: 9/15/21 - possible?
