### ISSUE TITLE
Password-Length: Relax password strength

### ISSUE THREAD

**Issue by roschaefer** [tactilenews/100eyes#969]
We're already using 2FA and yet we enforce a password length of at least 20 characters(!).

![swappy-20210716_134326](https://user-images.githubusercontent.com/2110676/125942507-00057921-5bf9-4bf7-a92b-36f09c9813df.png)

I think this is overkill. I'm sitting in a demo in which a group of users was onboarded. They had some difficulties to come up with such a long password.

**Comment by drjakob** [comment]
Please set to 8 character minimum
