### ISSUE TITLE
Onboarding su-page for Signal

### ISSUE THREAD

**Issue by drjakob** [tactilenews/100eyes#993]
As Editor,
I want to have an onboarding option for Signal 
in order to invite new contributors to contribute via Signal messenger.

**Comment by FrauCsu** [comment]
Sort of weird experience during onboarding: I write the requested hello to the number displayed, but never get an ok or an answer for it. I also don't know whether my onboarding is completed until I finally receive a regular request from an editor. So there is a piece of information missing during the onboarding process. @tillprochaska @phoeinx
